.PHONY: help install dev test lint fmt typecheck run scan up down migrate revision seed clean

help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-14s\033[0m %s\n", $$1, $$2}'

install: ## Install runtime + dev dependencies
	pip install -e ".[dev]"

test: ## Run the test suite
	pytest

lint: ## Lint with ruff
	ruff check app tests

fmt: ## Auto-format with ruff
	ruff check --fix app tests
	ruff format app tests

typecheck: ## Static type check with mypy
	mypy app

run: ## Run the FastAPI dev server
	uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

scan: ## Run a one-shot research scan from the CLI
	python -m app.cli scan

up: ## Start the full stack via docker compose
	docker compose up --build

down: ## Stop the stack
	docker compose down

migrate: ## Apply database migrations
	alembic upgrade head

revision: ## Create a new autogenerated migration (msg=...)
	alembic revision --autogenerate -m "$(msg)"

seed: ## Seed the default universe + risk policy
	python -m app.cli seed

clean: ## Remove caches and build artifacts
	rm -rf .pytest_cache .mypy_cache .ruff_cache *.egg-info build dist
	find . -type d -name __pycache__ -exec rm -rf {} +
