"""Structured contracts for the multi-agent research pipeline.

Agents exchange these models, never prose. Import from the submodules for
clarity; this package re-exports the names most call sites need.
"""

from app.multiagent.models.brief import (
    CompanyCatalyst,
    IndexContext,
    MacroEvent,
    MarketBrief,
    NewsReference,
    RiskEvent,
    SectorObservation,
    SourceReference,
    VIXContext,
)
from app.multiagent.models.candidates import (
    ExpectedMove,
    PreliminaryQuality,
    ResearchCandidate,
    SupportingCatalyst,
)
from app.multiagent.models.contracts import ProposedLeg, ProposedStructure
from app.multiagent.models.enums import (
    MARKET_STRATEGIES,
    AgentName,
    BiasDirection,
    CalibrationStatus,
    CatalystScope,
    CatalystType,
    Classification,
    DataQualityFlag,
    DecisionAction,
    Direction,
    EvidenceKind,
    EvidenceQuality,
    ExpectedDirection,
    Importance,
    MarketRegime,
    MeasurementStatus,
    PipelineStage,
    RejectionCode,
    RunStatus,
    StrategyType,
    TimeHorizon,
    ValidationVerdict,
    VolatilityRegime,
)
from app.multiagent.models.evidence import EvidenceItem, EvidenceLedger, make_evidence_id
from app.multiagent.models.measurements import (
    AbsenceReason,
    Measurement,
    MeasurementSet,
    Provenance,
)
from app.multiagent.models.report import (
    RankedReport,
    RankedTrade,
    RejectedTrade,
    RunDiagnostics,
    TradeDecision,
    TradeExecution,
    TradeResult,
)
from app.multiagent.models.runs import (
    AgentRunRecord,
    DataQualityRecord,
    PipelineRun,
    ProviderRequestRecord,
)
from app.multiagent.models.scoring import (
    CompositeScore,
    ScoreComponent,
    ScoredCandidate,
    ScoreRule,
)
from app.multiagent.models.validation import (
    CatalystValidation,
    ContractQualitySnapshot,
    FlowSnapshot,
    MarketAlignmentSnapshot,
    RiskRewardSnapshot,
    TechnicalSnapshot,
    ValidationReport,
)

__all__ = [
    "MARKET_STRATEGIES",
    "AbsenceReason",
    "AgentName",
    "AgentRunRecord",
    "BiasDirection",
    "CalibrationStatus",
    "CatalystScope",
    "CatalystType",
    "CatalystValidation",
    "Classification",
    "CompanyCatalyst",
    "CompositeScore",
    "ContractQualitySnapshot",
    "DataQualityFlag",
    "DataQualityRecord",
    "DecisionAction",
    "Direction",
    "EvidenceItem",
    "EvidenceKind",
    "EvidenceLedger",
    "EvidenceQuality",
    "ExpectedDirection",
    "ExpectedMove",
    "FlowSnapshot",
    "Importance",
    "IndexContext",
    "MacroEvent",
    "MarketAlignmentSnapshot",
    "MarketBrief",
    "MarketRegime",
    "Measurement",
    "MeasurementSet",
    "MeasurementStatus",
    "NewsReference",
    "PipelineRun",
    "PipelineStage",
    "PreliminaryQuality",
    "ProposedLeg",
    "ProposedStructure",
    "Provenance",
    "ProviderRequestRecord",
    "RankedReport",
    "RankedTrade",
    "RejectedTrade",
    "RejectionCode",
    "ResearchCandidate",
    "RiskEvent",
    "RiskRewardSnapshot",
    "RunDiagnostics",
    "RunStatus",
    "ScoreComponent",
    "ScoreRule",
    "ScoredCandidate",
    "SectorObservation",
    "SourceReference",
    "StrategyType",
    "SupportingCatalyst",
    "TechnicalSnapshot",
    "TimeHorizon",
    "TradeDecision",
    "TradeExecution",
    "TradeResult",
    "VIXContext",
    "ValidationReport",
    "ValidationVerdict",
    "VolatilityRegime",
    "make_evidence_id",
]
